### ISSUE TITLE
ImportError: No module named pulseeq

### ISSUE THREAD

**Issue by logix2** [pulseaudio-equalizer-ladspa/equalizer#18]
I'm trying to run this on an Ubuntu 18.04 computer but I'm getting this error:

```
$ pulseaudio-equalizer-gtk 
Traceback (most recent call last):
  File "/usr/bin/pulseaudio-equalizer-gtk", line 10, in <module>
    from pulseeq import equalizer
ImportError: No module named pulseeq
```

All files seem to be installed:

```
$ sudo ninja install
[0/1] Installing files.
Installing subdir /home/logix/Downloads/equalizer-3.0.0/data/presets to /usr/share/pulseaudio-equalizer-ladspa/presets
Installing data/com.github.pulseaudio-equalizer-ladspa.Equalizer.gresource to /usr/share/pulseaudio-equalizer-ladspa/com.github.pulseaudio-equalizer-ladspa.Equalizer.gresource
Installing /home/logix/Downloads/equalizer-3.0.0/build/bin/pulseaudio-equalizer-gtk to /usr/bin
Installing /home/logix/Downloads/equalizer-3.0.0/build/bin/pulseaudio-equalizer to /usr/bin
Installing /home/logix/Downloads/equalizer-3.0.0/data/com.github.pulseaudio-equalizer-ladspa.Equalizer.desktop to /usr/share/applications
Installing /home/logix/Downloads/equalizer-3.0.0/pulseeq/equalizer.py to /usr/lib/python3.6/site-packages/pulseeq
```

Any ideas?

**Comment by FFY00** [comment]
Can you run `env python --version`?

**Comment by raetiacorvus** [comment]
If i remember correctly pymod.find_installation() uses the python version meson uses that looks like python 3.6 in this case while `/usr/bin/env python` in `pulseaudio-equalizer-gtk` will most likely point to python 2 in ubuntu 18.04. We need to set it to the python version used for the installation. Sorry my mistake.
https://github.com/pulseaudio-equalizer-ladspa/equalizer/blob/20fb09cc3288995206f87d427e4b3f08dc34710c/meson.build#L7

**Comment by logix2** [comment]
Thanks. I guess I'll have to wait for the new release (not far though :) ).

**Comment by raetiacorvus** [comment]
Hi,

looks like mesons python module and its function python.install_sources
ignores that ubuntu uses dist-packages in sys.path rather then
site-packages. This probably comes from this bug
https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092.

For now you should be able to run the application by adding the module to
the python path e.g. with /usr/local as prefix
`PYTHONPATH=/usr/local/lib/python3.6/site-packages
pulseaudio-equalizer-gtk`.

logix2 <notifications@github.com> schrieb am Mo., 22. Okt. 2018 um
13:26 Uhr:

**Comment by logix2** [comment]
That works, thanks!

**Comment by FFY00** [comment]
Tou probably can make this work out of the box by setting the meson prefix to `/usr`.

**Comment by logix2** [comment]
I actually built the package with ``meson --prefix=/usr`` (so I used ``PYTHONPATH=/usr/lib/python3.6/site-packages pulseaudio-equalizer-gtk``).

**Comment by FFY00** [comment]
We should add a option to set the python path.
