### ISSUE TITLE
Bug after the last update

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [pulseaudio-equalizer-ladspa/equalizer#20]
I use Manjaro KDE latest version. After the last update, I need to open PulseAudio Equalizer all the time to keep the preset I choose, otherwise it goes back to the default preset after receiving a new audio stream.

**Comment by FFY00** [comment]
Which update? Manjaro delays Arch's packages so I have no clue what version you are running.

**Comment by ahmed-elsayed2017** [comment]
I am sorry. It is version 3.0.1-1.

**Comment by FFY00** [comment]
So it's up-to-date with master.

**Comment by ahmed-elsayed2017** [comment]
The first time using this application, I had to open it every time I restart my computer in order to activate it, but in the previous version I didn't have to do that and I was very happy, because when I enable Full-Bass preset, I can hear the voice accurately and that helps when listening to English, because it is not my native language, so thank so much you for this application, and I hope that you can fix it soon.

**Comment by ahmed-elsayed2017** [comment]
To clear things up, I don't mind keep the application opened all the time, but it doesn't work that way either.
When I keep the application opened and play any video, then close the video and open it again, I have to disable the equalizer and enable it again while the application still opened.

**Comment by FFY00** [comment]
That's weird. Do you have any other application modifying pulseaudio's config?

**Comment by raetiacorvus** [comment]
I was able to reproduce this issue on Manjaro KDE but I am not sure yet what causes this behavior. It looks like the ladspa module stays loaded with the correct parameters and is set as default sink but for whatever reason new audio streams e.g. even reloading a youtube video page will switch back to play on the old default sink even though KDE audio controls show that the ladspa module is still the default one.

**Comment by FFY00** [comment]
Really weird. I have no problems at all in Arch. Maybe it's a KDE thing? Perhaps it has, or ships with an app with, some kind of integration with pulseaudio. I am running Budgie which is Gnome based.

**Comment by raetiacorvus** [comment]
This is a KDE thing and already present in eqalizer-ladspa since at least v2.7.1 358553c

Dist | Issue Present
-----|---------------
Manjaro KDE | ✓
Manjaro KDE with minimal Gnome session | ✓
Kubuntu 18.10 | ✓
Manjaro Gnome | ✗
Arch Gnome | ✗

@ahmed-elsayed2017 In Phonon Audio and Video you can set the preferred audio playback device priority. Moving LADSPA Plugin to the top should fix your issue. 
![image](https://user-images.githubusercontent.com/1131371/47499495-60f61480-d860-11e8-9bbd-90fbd7f80a40.png)

**Comment by ahmed-elsayed2017** [comment]
Thanks, that solved the problem. Changing Audio playback doesn't change all the categories underneath it, so I changed them one by one just in case.

**Comment by ahmed-elsayed2017** [comment]
I changed audio configuration in Wine to use LADSPA Plugin Multiband EQ and everything is working alright right now.

**Comment by FFY00** [comment]
@raetiacorvus we should document this. I'll see if I have time.
