### ISSUE TITLE
Generated lines in default.pa

### ISSUE THREAD

**Issue by flittermice** [pulseaudio-equalizer-ladspa/equalizer#26]
First of all: Thanks, thanks, thanks for finally providing us a working EQ for pulseaudio (I use it on the Raspberry Pi) !!

I got an issue with the lines generated by `pulseaudio-equalizer enable-config`:
```
### Generated from: pulseaudio-equalizer
.nofail
load-module module-ladspa-sink sink_name=ladspa_output.mbeq_1197.mbeq sink_master=alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_DAC-00.analog-stereo plugin=mbeq_1197 label=mbeq control=5.6,4.2,1.0,0.0,-2.0,-3.1,-4.9,-5.6,-5.2,-2.8,0.0,2.0,3.0,4.2,5.2
set-default-sink ladspa_output.mbeq_1197.mbeq
set-sink-mute alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_DAC-00.analog-stereo 0
.endif
### END: Equalized audio configuration
```

This doesn't work. 
Pulseaudio log complains about `module-ladspa-sink.c: Failed to parse module arguments.`
and so on...

Or, manually on the command line:
```
pactl load-module module-ladspa-sink sink_name=ladspa_output.mbeq_1197.mbeq sink_master=alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_DAC-00.analog-stereo plugin=mbeq_1197 label=mbeq control=5.6,4.2,1.0,0.0,-2.0,-3.1,-4.9,-5.6,-5.2,-2.8,0.0,2.0,3.0,4.2,5.2
Failure: Module initialization failed
```

In contrast, `pulseaudio-equalizer enable` works without any problems.

BTW: 
Shouldn't it be **.fail** instead of **.endif**?

**Comment by flittermice** [comment]
To answer my own question:
Edit /usr/local/bin/pulseaudio-equalizer starting with line 299 and change `sink_master` to `master` and `.endif` to `.fail`.

**Comment by FFY00** [comment]
Sorry for the long wait, I have been busy.
