### ISSUE TITLE
Not working on Manjaro Gnome 18.04 

### ISSUE THREAD

**Issue by federicosnobohm** [pulseaudio-equalizer-ladspa/equalizer#30]
Is not working on Manjaro Gnome Arch Linux.

**Comment by FFY00** [comment]
How did you install it? Can you give any more details on how it isn't working? I'm on Archlinux and I can't reproduce.

**Comment by federicosnobohm** [comment]
I have installed from the AUR repository. (sorry for my english)
[pulseaudio-equalizer.log](https://github.com/pulseaudio-equalizer-ladspa/equalizer/files/3005772/pulseaudio-equalizer.log)
![Captura de pantalla de 2019-03-25 16-28-22](https://user-images.githubusercontent.com/35777568/54958485-8896f900-4f34-11e9-9096-9d3177630128.png)

**Comment by FFY00** [comment]
I haven't touched that package in a while, can you try the one in the official repos?

**Comment by federicosnobohm** [comment]
![Captura de pantalla de 2019-03-25 17-40-12](https://user-images.githubusercontent.com/35777568/54961132-42df2e00-4f3e-11e9-822a-b1c8184d41c2.png)
where is the package of the equalizer ? is that i chose in the image?

**Comment by FFY00** [comment]
No, the one below.

https://www.archlinux.org/packages/community/any/pulseaudio-equalizer-ladspa/

**Comment by federicosnobohm** [comment]
> No, the one below.
> 
> https://www.archlinux.org/packages/community/any/pulseaudio-equalizer-ladspa/

yes i install that package but still not working cant open 
![Captura de pantalla de 2019-03-25 17-47-39](https://user-images.githubusercontent.com/35777568/54961430-6656a880-4f3f-11e9-9714-f510951376ae.png)

**Comment by FFY00** [comment]
What do you mean you can't open? You don't see a `PulseAudio Equalizer` entry in your menu?

If not, try running `pulseaudio-equalizer-gtk` in the terminal.

**Comment by federicosnobohm** [comment]
yes i see the icon but the app never open i try it
![Captura de pantalla de 2019-03-25 17-59-18](https://user-images.githubusercontent.com/35777568/54961854-18db3b00-4f41-11e9-82c3-7b53cc787208.png)

**Comment by FFY00** [comment]
Hummm, that's definitely weird. Can you `cat /usr/bin/pulseaudio-equalizer-gtk`?

**Comment by federicosnobohm** [comment]
![Captura de pantalla de 2019-03-25 18-10-37](https://user-images.githubusercontent.com/35777568/54962142-8d62a980-4f42-11e9-8ea4-c43a640a6c20.png)
that?

**Comment by FFY00** [comment]
No, just see if `/usr/bin/pulseaudio-equalizer-gtk` contains anything inside, this seems weird.

**Comment by federicosnobohm** [comment]
![Captura de pantalla de 2019-03-25 18-20-48](https://user-images.githubusercontent.com/35777568/54962506-e3841c80-4f43-11e9-9a27-2d5f1d0f708b.png)
that?

**Comment by FFY00** [comment]
Yes. I have no idea what's going on. I can't reproduce.

**Comment by federicosnobohm** [comment]
It's really very weird because I could always use it on Manjaro Gnome, i try with Antergos Gnome and haves the same problem. :(

**Comment by glitsj16** [comment]
@federicosnobohm The log you posted always shows:

> ...
> PA_LADSPA_CONTROLS=,,,,,,,,,,,,,,,
> PA_LADSPA_INPUTS=,,,,,,,,,,,,,,,
> ...
> 

That's quite odd. Together with the rest of your issues it might be worthwhile to remove pulseaudio-equalizer-ladspa and reinstall from scratch. It might not explain what's going on, but in the screenshot you posted the version for pulseaudio-equalizer-ladspa shows 3.0.1-1. That's not the latest release, which is 3.0.2-1. I'm not familiar with Manjaro or Antergos, so these are standard pacman CLI commands to run:
```
$ sudo pacman -Rsn pulseaudio-equalizer-ladspa pulseaudio-equalizer-ladspa-git
$ sudo pacman -Syyuu
$ sudo pacman -S pulseaudio-equalizer-ladspa
$ pacman -Q pulseaudio-equalizer-ladspa
pulseaudio-equalizer-ladspa 3.0.2-1
```
If the version from the last command still shows something older, you might need to choose another repo mirror.

**Comment by FFY00** [comment]
```
sudo pacman -Sy pulseaudio-equalizer-ladspa
```

Should suffice.

**Comment by JerichoKru** [comment]
Allow me to chime in:  I had recently re-installed my system (Antergos) and previously had this plugin working.  This install, despite putting it back the way it was, i ran into the same problem that @federicosnobohm has.

I tried various things and then did this:

1. Deleted everything in `.config/pulse`
2. Killed pulse`pulseaudio -k` and restarted it `pulseaudio --start`

The GTK config program and the plugin started working.  The commands above were done as a normal user.  My fault may have been installing the -git version before this and it put down in invalid configuration that wasn't removed when I uninstalled it.

You can run `pulseaudio -v` as a normal user after killing pulseaudio to see more of what's going on.  In my case, pulseaudio said that the plugin itself was missing and couldn't load it.  This led me to look into where this plugin was storing configuration for itself, and saw `CONFIG_DIR="$HOME"/.config/pulse` in `pulseaudio-equalizer` and just decided to nuke the folder out of annoyance.  This may have been a bit overkill.

**Comment by federicosnobohm** [comment]
> Allow me to chime in: I had recently re-installed my system (Antergos) and previously had this plugin working. This install, despite putting it back the way it was, i ran into the same problem that @federicosnobohm has.
> 
> I tried various things and then did this:
> 
> 1. Deleted everything in `.config/pulse`
> 2. Killed pulse`pulseaudio -k` and restarted it `pulseaudio --start`
> 
> The GTK config program and the plugin started working. The commands above were done as a normal user. My fault may have been installing the -git version before this and it put down in invalid configuration that wasn't removed when I uninstalled it.
> 
> You can run `pulseaudio -v` as a normal user after killing pulseaudio to see more of what's going on. In my case, pulseaudio said that the plugin itself was missing and couldn't load it. This led me to look into where this plugin was storing configuration for itself, and saw `CONFIG_DIR="$HOME"/.config/pulse` in `pulseaudio-equalizer` and just decided to nuke the folder out of annoyance. This may have been a bit overkill.
> 
> I did save the old contents of the folder if anyone wants to look at it.

Thanks bro! thasta work for me!!
