### ISSUE TITLE
GTK issue?

### ISSUE THREAD

**Issue by Interknet** [pulseaudio-equalizer-ladspa/equalizer#35]
https://i.imgur.com/mb4aG89.png

On Manjaro KDE. Not sure what the issue is honestly.

**Comment by FFY00** [comment]
That doesn't have anything to do with this app. That's a warning in the GTK engine, it shouldn't affect our app at all.

**Comment by Interknet** [comment]
After running python3 /usr/lib/python3.7/site-packages/pulseeq/equalizer.py I get this error:

https://i.imgur.com/QAsxjIA.png

But the issue with the equalizer itself still remains; it doesn't open.

**Comment by FFY00** [comment]
That file isn't meant to be run. Use the file in your bin directory.
