### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by raetiacorvus** [pulseaudio-equalizer-ladspa/equalizer#4]
Hi i am working on a tentative gnome 3 redesign of the application. This issue is more of a question if upstream is even interested in one or not.

Original design for comparison.
![original_window](https://user-images.githubusercontent.com/1131371/46148474-7891ab80-c268-11e8-8dcb-670a5ac13275.png)

What I tried to do with this redesign is to get rid of the controls to the right of the equalizer panel and the advanced menu and move them either to the headerbar or the app menu to be more consistent with the rest of a modern gnome 3 desktop.

![redesign_flat_off](https://user-images.githubusercontent.com/1131371/46148366-34061000-c268-11e8-9b5c-75747d8bf020.png)

![app-menu](https://user-images.githubusercontent.com/1131371/46148467-716a9d80-c268-11e8-8c71-66ebbb81a4cc.png)

Both `Keep Settings` and `Reset to defaults` have moved to the app menu. I think `Keep Settings` is fine there. I am not really happy with the `Reset to defaults` option in general since it is pretty unclear to the user what gets reseted and what not. For now i want to keep it there till better more specific options are provided (e.g. reset option for preset changes that haven't been saved yet).

Changing `EQ Enabled` to a switch and moving it to the top right is consistent in how gnome-tweaks and gnome-control-center solved this for enabling/disabling a panel altogether. This also makes the window title displaying this state obsolete.

The explicit `Apply Settings` option has been removed. It was mostly useful to apply changed equalizer scales while in many other cases the application applies those settings automatically. The app now automatically applies settings on the button and key release events on the scales.

The presets text combobox is now the custom title of the headerbar. In theory this is great but has one big problem that it inherits from the original design. The popover isn't scrollable and will ignore your screen boundaries making some options not selectable if you have a long list of presets.
Long term it probably needs a customized combobox widget with a custom model. This would also make it possible to display additional information in the list e.g. if preset is a system or a user one. A rework of the presets into a proper class would probably be helpful here.

Both the `Save Preset` button and `Remove user preset…` option from the advanced menu are now preset sensitive buttons in the headerbar.

User presets can now be deleted directly when selected allowing to get rid of the filechooser dialog based system.

The save system works still like in the original app with all its flaws. It still isn't possible to overwrite an existing user preset. Typing the name of an existing preset will load it and overwrite any previously made changes.

e.g. assume you start with the `Perfect EQ` preset, after you change any scale the preset field will be empty and would fail silently if you try to save it without a name. Now you want to name your preset `Perfect EQ personalized` but once you typed `Perfect EQ` that preset would load and overwrite any changes you made.

I dabbled around with changing the save system but i think that it would be better to postponed after the presets and presets combobox have been reworked.

![redesign_flat_custom](https://user-images.githubusercontent.com/1131371/46160574-5fe2bf00-c283-11e8-8280-c3bef81934bb.png)

![redesign_flat_custom_saved](https://user-images.githubusercontent.com/1131371/46160627-856fc880-c283-11e8-9044-579a35bd8d0f.png)

**Comment by FFY00** [comment]
Great to hear! Upstream is abandoned so I don't think they would have any interest. We could keep the project maintained the best we can. I could perhaps create an organization for this.

**Comment by raetiacorvus** [comment]
Sounds good to me.

**Comment by FFY00** [comment]
We I invited you, I'll give you write access but we should still create pull requests to allow the other members to review the changes.

**Comment by raetiacorvus** [comment]
#10 solves this for now

**Comment by DwarfFighterCleric** [comment]
I use this app daily for 3 years (the old regular version displayed above)
I don't think it's useful "applying changes" immediately like you said, because by doing this the user can't notice the differences compared to before changing them, which in the end would make usability harder. That's my 2 cents.
And I still don't understand exactly what the "Keep Settings" button does exactly after all this time, I mostly never use it xDDD
