### ISSUE TITLE
Binary package not present in distros main repositories anymore?

### ISSUE THREAD

**Issue by DwarfFighterCleric** [pulseaudio-equalizer-ladspa/equalizer#52]
Any reason for why pulseaudio-equalizer-ladspa is not present in major distributions' repositories anymore?  
Is there a custom PPA that I can add that has this package?  
Do you still have binaries packages for the older version present in Ubuntu Xenial around 2017-ish? I like that version more, because it doesn't immediately applies changes while you are changing values, you have to press button "Apply Changes".  
But this new version seems to cause less stutterings with Pulseaudio, less bugs I guess, so well done :)  
I just don't like the new UI, it's too easy to make mistakes adjusting boosts/cuts, the sliders move too fast, specially on crappy laptop touchpad.

**Comment by DwarfFighterCleric** [comment]
OK this is something that intrigues me, I'm certain that I was able to find this package for Ubuntu-Debian distros in the past. Now I can only find packages for Arch and Manjaro?  
Do you have built Debian packages anywhere? Can you include them in releases?  
Not sure what's happening. I tried installing the regular "pulseaudio-equalizer" package, but that one - on top of requiring me to set up the modules and sink manually, urgh! - doesn't look anything like I remember it, it doesn't even come with default Presets anymore.  
What's happening? Can anyone explain to me what it is all about? Why all the de-evolution? It worked in the past, it was brilliant.

**Comment by rsubtil** [comment]
I believe `pulseaudio-equalizer` and `pulseaudio-equalizer-ladspa` *(this one)* are different projects, with this one based on the former.

This project has been unmaintained for quite some time (#47), so that's likely why it's now missing on major distros repositories.

**Comment by DwarfFighterCleric** [comment]
Nevermind, the package that I've used in the past is a 3rd one, it's in an independent repository PPA called "Webupd8"  
Links to packages here: https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+packages?field.name_filter=pulseaudio&field.status_filter=published&field.series_filter=  
That is the version that not only looks better, but also has more functionality, despite being older (executable date 2016)  
To install this package manually, adding the PPA to your sources list won't work, because Apt-Get will think that you want the regular pulseaudio-equalizer (version 12.x ... the one that requires the user to manually add pulse module... totally unnaceptable, and doesn't even come with any default presets...)  

    (this here won't work, just here for reference)
    sudo apt-get install software-properties-common  

(this linux distro doesn't come with the feature add-apt built-in by default? what are these linux guys doing these days? do you have to gain a few extra Kilobytes in your ISO size? doesn't make any sense! what even is this???  

    sudo add-apt-repository ppa:nilarimogard/webupd8
    sudo apt-get update

SOLUTION: These commands below will install the dependencies, and you will be able to circumvent the python-gnome2 package that isn't available anymore:  

    sudo apt-get install swh-plugins ladspa-sdk
    sudo dpkg -i --ignore-depends=python-gnome2 /home/path/pulseaudio-equalizer_2.7.0.2-5_webupd8_xenial0_all.deb  

It's working with MX Linux 19.3 AHS Nov-2020 release (based on Debian 10 Buster)  
Everything works automatically, you don't need to mess around with Pulse config files and WASTE time anymore.
Initialize tool from Xfce Whisker menu with mouse.
The amount of work to get a simple thing going these days. These guys are ruining Linux.

**Comment by DwarfFighterCleric** [comment]
pulseaudio-equalizer-ladspa is another project, and packages seem to be only available for Arch and Manjaro, for whatever stupid reason...  
That one also does NOT require the user to manually edit pulse configs, and also comes with default Presets.  
The only package readily available for Debian users is this one right here, the worse of them all. Avoid it. Lazy half assed work.
